// <auto-generated />
namespace UrunYonetim6584.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SliderEklendi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SliderEklendi));
        
        string IMigrationMetadata.Id
        {
            get { return "202306031111444_SliderEklendi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
